volume=30
script-opts=ytdl_hook-ytdl_path=yt-dlp
hwdec=auto
osd-bar=no

[stream-30s]
profile-desc=30 second resilient streaming buffer
cache=yes
cache-secs=30
cache-pause=yes
cache-pause-initial=yes
cache-pause-wait=30
demuxer-max-bytes=256MiB
demuxer-max-back-bytes=64MiB

[fast]
profile=fast
vo=gpu-next
gpu-api=d3d11
gpu-context=d3d11
hwdec=auto
video-sync=audio
interpolation=no
deband=no
framedrop=vo
priority=normal
d3d11va-zero-copy=yes
